#! /bin/sh

# Hotkey daemon
sxhkd &
# Compositor
picom -b
# Wallpaper
~/.fehbg &
wal -neR
# Notification server
dunst &
# WiFi menu
nm-applet &
# Bluetooth manager
blueman-applet &
# Volume bar
tail -f xobvolpipe | xob -s volume &
# Brighness bar
tail -f xobbklpipe | xob -s backlight &
# Status bar
$HOME/.config/polybar/launch.sh
# Touchpad gestures
gebaard -b
# Lock screen
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_AUTH_BACKGROUND_COLOR='#efed86' XSECURELOCK_AUTH_FOREGROUND_COLOR='#212121' XSECURELOCK_FONT='iosevka' xsecurelock &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config border_radius        3

bspc config borderless_monocle   true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color4"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color3"
bspc config presel_border_color "$color4"
