[commands.swipe.three]
left_up = ""
right_up = ""
up = "bspc node -f north"
left_down = ""
right_down = ""
down = "bspc node -f south"
left = "bspc node -f west"
right = "bspc node -f east"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "rofi -show drun -show-icons"
left_down = ""
right_down = ""
down = ""
left = "bspc desktop -f next"
right = "bspc desktop -f prev"
