#! /bin/sh

# Hotkey daemon
sxhkd &
# Compositor
picom -b
# Wallpaper
~/.fehbg &
wal -neR
# Notification server
dunst &
# WiFi menu
nm-applet &
# Bluetooth manager
blueman-applet &
# Optimus manager GUI
optimus-manager-qt &
# IBus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx
# Volume bar
tail -f xobvolpipe | xob -s volume &
# Brighness bar
tail -f xobbklpipe | xob -s backlight &
# MPD notifications
python $HOME/notify-mpd.py &
# Status bar
$HOME/.config/polybar/launch.sh
# Touchpad gestures
$HOME/.config/gebaar/launch.sh
# Lock screen
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_AUTH_BACKGROUND_COLOR='#efed86' XSECURELOCK_AUTH_FOREGROUND_COLOR='#212121' XSECURELOCK_FONT='iosevka' xsecurelock &

bspc monitor -d I II III IV V VI VII VIII IX X
# When an external monitor is connected through the HDMI port
# bspc monitor eDP-1 -d I II III IV V
# bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config window_gap            6
bspc config border_width          1
bspc config border_radius         3
bspc config gapless_monocle       true
bspc config borderless_monocle    true
bspc config focus_follows_pointer true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color4"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color3"
bspc config presel_border_color "$color4"

bspc rule -a discord desktop=^3
