#! /bin/sh

# Autostart programs

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Wallpaper
~/.fehbg

# Compositor
picom --experimental-backends -b

# Notification server
dunst &

# Kill previous xob instances
pkill xob

# Volume bar
tail -f xobvolpipe | xob -s volume &

# Brightness bar
tail -f xobbklpipe | xob -s backlight &

# Status bar
$HOME/.config/polybar/launch.sh

# MPD notifications
$HOME/scripts/mpd_notifications.py &

# Input method framework
fcitx5 &

# MPD
[ ! -s ~/.config/mpd/pid ] && mpd

# Touchpad gestures
libinput-gestures-setup start

# Lockscreen
xset s 600 10
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_PAM_SERVICE="xscreensaver" XSECURELOCK_AUTH_BACKGROUND_COLOR='#000000' XSECURELOCK_AUTH_FOREGROUND_COLOR='#FFFFFF' XSECURELOCK_FONT='iosevka' XSECURELOCK_COMPOSITE_OBSCURER=0 XSECURELOCK_SAVER='saver_feh' XSECURELOCK_IMAGE_PATH="$HOME/Pictures/lockscreen.jpg" XSECURELOCK_BLANK_TIMEOUT=15 XSECURELOCK_WAIT_TIME_MS=10 xsecurelock &

# bspwm config

# bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# bspc monitor DP-1 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX

bspc config border_width           1
bspc config window_gap             10

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        false
bspc config left_monocle_padding   -10
bspc config right_monocle_padding  -10
bspc config bottom_monocle_padding -10
bspc config focus_follows_pointer  true

# Set the border colors.
bspc config normal_border_color   "#858585"
bspc config active_border_color   "#efe383"
bspc config focused_border_color  "#000000"
bspc config presel_border_color   "#efe383"

# Rules to open certain apps in specific desktops by default
bspc rule -a Pavucontrol desktop=^6
bspc rule -a Transmission-gtk desktop=^10
bspc rule -a discord desktop=^11
bspc rule -a Anki desktop=^12
bspc rule -a zoom desktop=^13
bspc rule -a Element desktop=^14
bspc rule -a Anydesk desktop=^19
bspc rule -a Thunderbird desktop=^20
bspc rule -a Mailspring desktop=^20
